# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  test:
    desc: "Запуск Go тестов через Docker"
    dir: "{{.GEN_GO_DIR}}"
    cmds:
      - |
        docker run --rm \
          -v "{{.USER_WORKING_DIR}}:/workspace" \
          -w /workspace \
          -e GOCACHE=/tmp/go-cache \
          -e GOPATH=/tmp/go-path \
          --user $(id -u):$(id -g) \
          golang:alpine \
          go test -v ./...
